# Generated by Django 3.1.4 on 2021-01-03 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('technology', models.CharField(max_length=250)),
                ('main_image', models.FileField(upload_to='img/')),
                ('source_code', models.CharField(max_length=50)),
                ('img1', models.FileField(upload_to='img/')),
                ('img2', models.FileField(upload_to='img/')),
                ('img3', models.FileField(upload_to='img/')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.FileField(upload_to='img/')),
                ('skills', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
