# Generated by Django 3.1.4 on 2021-01-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(path='F:\\django_projects\\personal_portfolio\\portfolio\\static\\img'),
        ),
    ]
