# Generated by Django 3.1.4 on 2021-01-21 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_followersfield_followingfield_notificationsfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsfield',
            name='Pid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='notificationsfield',
            name='read',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationsfield',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.newfields'),
        ),
    ]
